openapi: 3.0.0
info:
  title: Cheese API
  description: A simple API to manage cheese data
  version: "1.0.0"
servers:
  - url: http://localhost:5001
    description: Local development server

paths:
  /cheese:
    get:
      summary: Get a list of all cheeses
      operationId: getCheeses
      tags:
        - Cheeses
      responses:
        "200":
          description: A list of cheeses
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: Cheddar
                    pricePerKilo:
                      type: number
                      format: float
                      example: 15.00
                    color:
                      type: string
                      example: Yellow
                    imageUrl:
                      type: string
                      example: images/cheddar.jpg
        "500":
          description: Server error

components:
  schemas:
    Cheese:
      type: object
      properties:
        id:
          type: integer
          description: The cheese ID
        name:
          type: string
          description: The name of the cheese
        pricePerKilo:
          type: number
          description: The price per kilogram of the cheese
          format: float
        color:
          type: string
          description: The color of the cheese
        imageUrl:
          type: string
          description: The URL of the cheese image
      required:
        - id
        - name
        - pricePerKilo
        - color
        - imageUrl
